apiVersion: skaffold/v4beta11
kind: Config
metadata:
  name: db-runbooks
build:
  artifacts:
    - image: aqsh-mariadb
      context: aqsh-tasks
      docker:
        dockerfile: Dockerfile
        buildArgs:
          TASKS_YAML: tasks-mariadb.yaml
    - image: aqsh-mongodb
      context: aqsh-tasks
      docker:
        dockerfile: Dockerfile
        buildArgs:
          TASKS_YAML: tasks-mongodb.yaml
  local:
    push: false
    useBuildkit: true
deploy:
  kubectl: {}
