apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx
  namespace: db-ops
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
        - name: nginx
          image: nginx:alpine
          ports:
            - name: http
              containerPort: 80
            - name: stream-mongo-1
              containerPort: 30092
            - name: stream-mariadb-1
              containerPort: 30093
            - name: stream-mongo-2
              containerPort: 30094
            - name: stream-mariadb-2
              containerPort: 30095
            - name: stream-mongo-3
              containerPort: 30096
            - name: stream-mariadb-3
              containerPort: 30097
          volumeMounts:
            - name: nginx-config
              mountPath: /etc/nginx/nginx.conf
              subPath: nginx.conf
          livenessProbe:
            httpGet:
              path: /healthz
              port: 80
            initialDelaySeconds: 5
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /healthz
              port: 80
            initialDelaySeconds: 5
            periodSeconds: 10
      volumes:
        - name: nginx-config
          configMap:
            name: nginx-config
