apiVersion: v1
kind: Secret
metadata:
  name: mariadb
  namespace: db-2
stringData:
  password: db2-root-pass
---
apiVersion: k8s.mariadb.com/v1alpha1
kind: MariaDB
metadata:
  name: mariadb
  namespace: db-2
spec:
  rootPasswordSecretKeyRef:
    name: mariadb
    key: password
  port: 3306
  image: mariadb:10.11
  storage:
    size: 1Gi
