apiVersion: v1
kind: Secret
metadata:
  name: mariadb
  namespace: db-3
stringData:
  password: db3-root-pass
---
apiVersion: k8s.mariadb.com/v1alpha1
kind: MariaDB
metadata:
  name: mariadb
  namespace: db-3
spec:
  rootPasswordSecretKeyRef:
    name: mariadb
    key: password
  port: 3306
  image: mariadb:11.4
  storage:
    size: 1Gi
