apiVersion: v1
kind: Secret
metadata:
  name: mariadb
  namespace: db-1
stringData:
  password: db1-root-pass
---
apiVersion: k8s.mariadb.com/v1alpha1
kind: MariaDB
metadata:
  name: mariadb
  namespace: db-1
spec:
  rootPasswordSecretKeyRef:
    name: mariadb
    key: password
  port: 3306
  image: mariadb:10.6
  storage:
    size: 1Gi
